#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
TOTAL_MINUTES=45

if [[ $# -ne 1 || "$1" != /* ]]; then
  say "Usage: bash scripts/private-input-wizard.sh /absolute/private/evidence-directory"
  exit 2
fi
if [[ ! -t 0 ]]; then
  say "This wizard requires a human at an interactive terminal in the private analysis account."
  exit 2
fi
umask 077
WORK_DIR="$1"
PYTHON_RUNTIME="${PYTHON_RUNTIME:-python3}"
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
INSPECTOR="$SCRIPT_DIR/input_evidence.py"
GUIDE_FILE="$SCRIPT_DIR/../docs/private-input-evidence.md"
ENV_FILE="$WORK_DIR/wizard.env"

if ! "$PYTHON_RUNTIME" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 2)'; then
  warn "Python 3.11 or newer is required. Set PYTHON_RUNTIME to its executable path."
  exit 2
fi

say "Private input evidence — 6 stages, about 45 minutes plus any native-format preparation."
say "Use a local offline editor. Stop at any time; rerunning starts the stages again with saved JSON files."
warn "Only you may run this with real inputs, in the private analysis account. Never run an agent there."
confirm "Are you in the private analysis account with a private working directory?" || exit 0

stage "Input inventory" 8
if [[ -e "$WORK_DIR" ]]; then
  [[ -f "$WORK_DIR/inventory.json" && -f "$WORK_DIR/review.json" ]] || {
    warn "Existing directory is not an initialized evidence directory. Choose a new directory."
    exit 2
  }
  confirm "Resume the existing private evidence files and regenerate observations?" || exit 0
else
  "$PYTHON_RUNTIME" "$INSPECTOR" init --work-dir "$WORK_DIR"
fi
# The preserved write_env helper uses mktemp: keep its intermediate files private too.
export TMPDIR="$WORK_DIR"
INVENTORY_FILE="$WORK_DIR/inventory.json"
REVIEW_FILE="$WORK_DIR/review.json"
OBSERVATIONS_FILE="$WORK_DIR/observations.json"
CANDIDATE_FILE="$WORK_DIR/candidate-summary.md"
write_env PYTHON_RUNTIME "$PYTHON_RUNTIME"
write_env BASH_RUNTIME "$BASH_VERSION"
write_env INVENTORY_FILE "$INVENTORY_FILE"
write_env REVIEW_FILE "$REVIEW_FILE"
write_env OBSERVATIONS_FILE "$OBSERVATIONS_FILE"
write_env CANDIDATE_FILE "$CANDIDATE_FILE"
step "Open the guide in your offline editor: $GUIDE_FILE"
step "Follow Stage 1 to edit $INVENTORY_FILE — list every input, not just an assumed pair of CSVs."
say "Record private paths, native formats, tables/sheets and release evidence; use unknown where necessary."
confirm "Have you saved the inventory and kept release evidence private?" || exit 0
if ! "$PYTHON_RUNTIME" "$INSPECTOR" inventory --work-dir "$WORK_DIR"; then
  warn "Inventory is incomplete. Correct paths/configuration using the guide, then rerun."
  exit 2
fi
write_env INVENTORY_REVIEWED yes

stage "Serialization" 7
step "Follow Stage 2 in the guide; edit serialization settings in $INVENTORY_FILE."
say "Supply known encoding, delimiter, quote/escape rules and header record number. Leave unknown settings null."
say "Native workbooks/statistical formats require private manual review and a separately verified conversion."
confirm "Have you saved the parsing declarations or explicitly left them unresolved?" || exit 0
if ! "$PYTHON_RUNTIME" "$INSPECTOR" inspect --work-dir "$WORK_DIR"; then
  warn "Some inputs failed inspection. Fixed-status observations remain private; follow the guide to diagnose."
  confirm "Continue to document incomplete evidence and blockers?" || exit 0
fi
write_env SERIALIZATION_REVIEWED yes

stage "Schema compatibility" 5
step "Open $OBSERVATIONS_FILE locally and review schema counts and missing documented fields."
step "In $REVIEW_FILE, record private v2 evidence under v2_compatibility."
say "A match with the older JSON dictionary cannot confirm v2 equivalence. Unknown headers are not released."
confirm "Have you recorded v2 compatibility as confirmed from private evidence or unresolved?" || exit 0
write_env SCHEMA_REVIEWED yes

stage "Required characteristics" 10
step "Follow Stage 4: review identifier, linkage, target-conflict, indicator-state and age-number counts."
step "Edit missing_tokens and indicator_blank_mapping in $INVENTORY_FILE only from private evidence."
step "Record identifier preservation, age at death, missing conventions and undetermined meaning in $REVIEW_FILE."
say "Private evidence references stay private. Write separate release-safe convention statements only if justified."
confirm "Have you saved conventions and their verification status without inventing unknown meanings?" || exit 0
if ! "$PYTHON_RUNTIME" "$INSPECTOR" inspect --work-dir "$WORK_DIR"; then
  warn "Inspection remains incomplete. Do not treat these inputs as ready."
  confirm "Continue to preparation decisions with these blockers?" || exit 0
fi
write_env CHARACTERISTICS_REVIEWED yes

stage "Preparation requirements" 10
step "Follow Stage 5 and record conversion/mapping needs and unresolved questions under preparation in $REVIEW_FILE."
say "The target remains two UTF-8 CSV inputs. Preserve identifier strings, indicator states and exact target labels."
say "No conversion, normalization, cause pooling or benchmark fitting is performed by this wizard."
confirm "Have you recorded a preparation decision, or the unresolved work needed to reach one?" || exit 0
write_env PREPARATION_REVIEWED yes

stage "Review and handoff" 5
step "Follow Stage 6: open $REVIEW_FILE and choose release_sections and individual release_approved flags."
say "Approve only necessary format/schema facts, conventions and aggregates. Review small counts for disclosure."
confirm "Generate a PRIVATE DRAFT using only the sections and statements you selected?" || exit 0
"$PYTHON_RUNTIME" "$INSPECTOR" summary --work-dir "$WORK_DIR"
step "Review $CANDIDATE_FILE in your offline editor. Remove anything that must remain private."
say "Paths, records, private evidence, raw logs, predictions and fitted models must never leave this account."
say "After your final review, manually transfer only the approved summary, using the guide's destination."
pause "Press Enter after reviewing the draft and noting any remaining blockers."
SKIPPED+=("Human approval, manual evidence transfer and linking it from Ticket 01; Ticket 02 remains blocked until then.")
# Bash 3.2 treats empty arrays as unset under nounset. Only the preserved closing helper needs this allowance.
set +u
finish
set -u
say "Wizard stages finished. No evidence has been transferred and Ticket 01 is not yet complete."
